/* Original Work Copyright (c) 2021 Giuseppe Baccini - giuseppe.baccini@live.com

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
the Software, and to permit persons to whom the Software is furnished to do so,
subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

package util

import (
	"encoding/json"
)

type MsgKey string

const (
	MsgKeyPktType        = "_pt" //packet type
	MsgKeyPktSrcIP       = "_si" //packet source ip: the ip of the outgoing interface of the source host
	MsgKeyPktSrcLstnPort = "_lp" //packet source listening port: the listening port of the source host
	MsgKeyPktTS          = "_ts" //packet timestamp: the timestamp of the packet
	MsgKeyPktDataVal     = "_dv" //packet data: the value inside a Data packet (TCP)
	MsgKeyInterrupt      = "_ir" //packet interrupt: a key used to generate events inside the application (interrupts generated by selector/peer)
)

const (
	MsgPktTypeAlive = "an" //packet type value: Alive Node (UDP multicast)
	MsgPktTypeData  = "dt" //packet type value: Data (TCP)
)

/**
 * Alive message (UDP multicast):
 *
 *      {
 *       "_lp" : 31582,
 *       "_pt" : "an",
 *       "_si" : "172.17.0.2",
 *       "_ts" : 1612981749
 *      }
 */
type AliveMsg struct {
	Lp uint16 `json:"_lp"`
	Pt string `json:"_pt"`
	Si string `json:"_si"`
	Ts uint64 `json:"_ts"`
}

func (msg *AliveMsg) UnmarshalJSON(buffer []byte) error {
	return json.Unmarshal(buffer, msg)
}

func (msg *AliveMsg) MarshalJSON() ([]byte, error) {
	return json.Marshal(msg)
}

/**
 * An example of Data message (TCP):
 *
 *     {
 *      "_dv" : "Jerico",
 *      "_pt" : "dt",
 *      "_ts" : 1612981862
 *     }
 */
type DataMsg struct {
	Dv string `json:"_dv"`
	Pt string `json:"_pt"`
	Ts uint64 `json:"_ts"`
}

func (msg *DataMsg) UnmarshalJSON(buffer []byte) error {
	return json.Unmarshal(buffer, msg)
}

func (msg *DataMsg) MarshalJSON() ([]byte, error) {
	return json.Marshal(*msg)
}
